### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by audijiJQ** [LawPaul/MH2p_SD_ModKit#4]
"I discovered checksum and signing methods through reverse engineering MH2p binaries"
Hi,this signature is sha_1 pkcs7? can you talk how to make it ?

**Comment by LawPaul** [comment]
No. The mod kit allows you to run any unsigned code you want. Making the signing irrelevant.

**Comment by audijiJQ** [comment]
It looks like this, but I am very curious about the process of this signature. It uses a short alternative signature, like ANS1 padding in PKCS7.
